In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
import csv
from copy import deepcopy
import random
import gc
from Preprocessing import Preprocessor
from Downloader import Extractor
from os import listdir
from os.path import isfile, join, isdir
from tqdm import tqdm_notebook
import utils.Preprocessing
import warnings
warnings.filterwarnings('ignore')

ImportError: No module named 'Preprocessing'

In [ ]:
import sys
# the mock-0.3.1 dir contains testcase.py, testutils.py & mock.py
sys.path.append('/foo/bar/mock-0.3.1')

from testcase import TestCase
from testutils import RunTests
from mock import Mock, sentinel, patch

In [17]:
station_list = [1801, 1804, 1808, 1813, 1805, 1820, 1821, 1831, 1899, 1911, #Кола
                1825, 1826, 1937, #Сорвала-Петрозаводск
                1068, 1074, 1081, #КАД
                895, 898, 882, 865, 867, 860, 879, #Холмогоры
                870, 873, #Вологда- Новая Ладога
                20743, #Москва-Дубна
                189, 202, 204, 207, 200, #Москва-СПб
                20754, 20755, 20761, #МБК
                20730, 20733, 223, 228, 239, #Балтия
                1926, 1921] #СПб-Невель

In [8]:
extractor = Extractor([113, 114, 115, 1820, 1804], [1, 2, 3, 4, 16], '2007-11-01', '2016-01-01')
z = extractor.ExtractFromDB('mysql://root:casper@localhost:3306/lmeteo3')

        station_id           date_time    data  sensor_type_id         type
0              113 2012-09-17 18:01:48  7357.0              16     pressure
1              113 2012-09-17 18:01:48   140.0               2       t_road
2              113 2012-09-17 18:01:48   136.0               1        t_air
3              113 2012-09-17 18:01:48   140.0               3  t_underroad
4              113 2012-09-17 18:01:48   831.0               4     dampness
5              113 2012-09-18 14:33:21  7398.0              16     pressure
6              113 2012-09-18 14:33:21   194.0               2       t_road
7              113 2012-09-18 14:33:21   156.0               1        t_air
8              113 2012-09-18 14:33:21   187.0               3  t_underroad
9              113 2012-09-18 14:33:21   664.0               4     dampness
10             113 2012-09-18 16:02:38  7398.0              16     pressure
11             113 2012-09-18 16:02:38   200.0               2       t_road
12             113 2012-09-18 16:02:38   157.0               1        t_air
13             113 2012-09-18 16:02:38   187.0               3  t_underroad
14             113 2012-09-18 16:02:38   646.0               4     dampness
15             113 2012-09-18 17:03:11  7398.0              16     pressure
16             113 2012-09-18 17:03:11   194.0               2       t_road
17             113 2012-09-18 17:03:11   152.0               1        t_air
18             113 2012-09-18 17:03:11   181.0               3  t_underroad
19             113 2012-09-18 17:03:11   674.0               4     dampness
20             113 2012-09-18 17:32:17  7406.0              16     pressure
21             113 2012-09-18 17:32:17   190.0               2       t_road
22             113 2012-09-18 17:32:17   147.0               1        t_air
23             113 2012-09-18 17:32:17   177.0               3  t_underroad
24             113 2012-09-18 17:32:17   692.0               4     dampness
25             113 2012-09-18 18:32:58  7406.0              16     pressure
26             113 2012-09-18 18:32:58   141.0               2       t_road
27             113 2012-09-18 18:32:58   135.0               1        t_air
28             113 2012-09-18 18:32:58   145.0               3  t_underroad
29             113 2012-09-18 18:32:58   764.0               4     dampness
...            ...                 ...     ...             ...          ...
838680         115 2015-12-31 21:06:00  -197.0               3  t_underroad
838681         115 2015-12-31 21:06:00   762.0              16     pressure
838682         115 2015-12-31 21:06:00  -221.0               2       t_road
838683         115 2015-12-31 21:06:00   905.0               4     dampness
838684         115 2015-12-31 21:06:00  -265.0               1        t_air
838685         115 2015-12-31 21:36:23   762.0              16     pressure
838686         115 2015-12-31 21:36:23  -198.0               3  t_underroad
838687         115 2015-12-31 21:36:23  -222.0               2       t_road
838688         115 2015-12-31 21:36:23   908.0               4     dampness
838689         115 2015-12-31 21:36:23  -264.0               1        t_air
838690         115 2015-12-31 22:06:39   904.0               4     dampness
838691         115 2015-12-31 22:06:39   762.0              16     pressure
838692         115 2015-12-31 22:06:39  -263.0               1        t_air
838693         115 2015-12-31 22:06:39  -223.0               2       t_road
838694         115 2015-12-31 22:06:39  -198.0               3  t_underroad
838695         115 2015-12-31 22:37:02   762.0              16     pressure
838696         115 2015-12-31 22:37:02   896.0               4     dampness
838697         115 2015-12-31 22:37:02  -277.0               1        t_air
838698         115 2015-12-31 22:37:02  -224.0               2       t_road
838699         115 2015-12-31 22:37:02  -199.0               3  t_underroad
838700         115 2015-12-31 23:07:23  -200.0               3  t_underroad
838701         115 2015-12-31 23:07:23   910.0               4     dampness
838702         115 2015-12-31 23:07:23  -271.0               1        t_air
838703         115 2015-12-31 23:07:23  -225.0               2       t_road
838704         115 2015-12-31 23:07:23   762.0              16     pressure
838705         115 2015-12-31 23:37:49  -201.0               3  t_underroad
838706         115 2015-12-31 23:37:49   762.0              16     pressure
838707         115 2015-12-31 23:37:49  -227.0               2       t_road
838708         115 2015-12-31 23:37:49   892.0               4     dampness
838709         115 2015-12-31 23:37:49  -275.0               1        t_air

[838710 rows x 5 columns]

In [3]:
sql_query = 'select * from station_def;'
db_connection = 'mysql://root:casper@localhost:3306/lmeteo3'
df = pd.read_sql(con=db_connection, sql=sql_query)

ImportError: No module named 'MySQLdb'